# Generated by Django 4.2 on 2023-04-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos_api', '0001_initial'),
        ('usuarios_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=125, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=125, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tamanio',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=125)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fk_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_api.estado')),
                ('fk_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas_api.prioridad')),
                ('fk_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_api.proyecto')),
                ('fk_tamanio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas_api.tamanio')),
            ],
            options={
                'db_table': 'tarea',
                'unique_together': {('nombre', 'fk_proyecto')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fk_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas_api.tarea')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_api.usuario')),
            ],
            options={
                'db_table': 'asignar_tarea',
                'unique_together': {('fk_tarea', 'fk_usuario')},
            },
        ),
    ]
