# Generated by Django 4.2 on 2023-04-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=125)),
                ('correo', models.CharField(max_length=125, unique=True)),
                ('clave', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
