# Generated by Django 4.2 on 2023-04-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='clave',
            new_name='password',
        ),
    ]
