# Generated by Django 4.2 on 2023-04-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_api', '0004_alter_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
    ]
